[package]
org = "hahack23"
name = "abcIDPConnect"
version = "1.2.6"
export = ["abcIDPConnect"]
distribution = "2201.3.1"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true

