[package]
org = "hahack23"
name = "jackhenryIDPConnect"
version = "1.1.5"
export = ["jackhenryIDPConnect"]
distribution = "2201.3.1"
keywords = ["choreo-apim-mediation-policy","choreo-apim-mediation-request-flow"]

[build-options]
observabilityIncluded = true

