[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["rdbsasrestservice"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "rdbsasrestservice"
  org = "hahack23"
  version = "3.1.1"

