[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.1.2"
  export = ["graphqldemo"]
  icon = "docs/icon.png"
  keywords = ["Type/GraphQL","Category/Service","Internal/http"]
  name = "graphqldemo"
  org = "hahack23"
  version = "1.0.1"

