[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["servicechainingdemo"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "servicechainingdemo"
  org = "choreodemona123"
  version = "3.1.0"

